// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqHcIOkXQkMLlUf-6w246Ss8H_djOwZ8',
    appId: '1:879288484629:web:00afe92524c46aea7edf1c',
    messagingSenderId: '879288484629',
    projectId: 'memla-daf2f',
    authDomain: 'memla-daf2f.firebaseapp.com',
    storageBucket: 'memla-daf2f.appspot.com',
    measurementId: 'G-CMXXBTVPHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdFYStu7F9I_siUTsVPscmUBBycs8wT1s',
    appId: '1:879288484629:android:b8653ffd96ea4f1b7edf1c',
    messagingSenderId: '879288484629',
    projectId: 'memla-daf2f',
    storageBucket: 'memla-daf2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3_DuCs21_2jFBRpZfSdaIBQF5uYlOTnM',
    appId: '1:879288484629:ios:6a01eeab808cda247edf1c',
    messagingSenderId: '879288484629',
    projectId: 'memla-daf2f',
    storageBucket: 'memla-daf2f.appspot.com',
    androidClientId: '879288484629-p5m7582o01k0lq63c35p5lc61i81jjna.apps.googleusercontent.com',
    iosClientId: '879288484629-am4oa3hdehi9ajrmqncb4l44kcm026br.apps.googleusercontent.com',
    iosBundleId: 'com.mla.memla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3_DuCs21_2jFBRpZfSdaIBQF5uYlOTnM',
    appId: '1:879288484629:ios:732ffcbe3cd6c3bb7edf1c',
    messagingSenderId: '879288484629',
    projectId: 'memla-daf2f',
    storageBucket: 'memla-daf2f.appspot.com',
    androidClientId: '879288484629-p5m7582o01k0lq63c35p5lc61i81jjna.apps.googleusercontent.com',
    iosClientId: '879288484629-b0hsvprv0582o6668b385d2jkbkp7lc9.apps.googleusercontent.com',
    iosBundleId: 'com.mla.memla.RunnerTests',
  );
}
